### ISSUE TITLE
FYI: maturin now support read `--cargo-extra-args` from pyproject.toml

### ISSUE THREAD

**Issue by messense** [cberner/redb#70]
See https://github.com/PyO3/maturin/pull/605, just need to add it to `[tool.maturin]` section for example

```toml
[tool.maturin]
cargo-extra-args = "--features python"
```

and `maturin build` would work automatically.
